import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from "react";

import MenuRoundedIcon from '@mui/icons-material/MenuRounded';

import Stack from '../libs/stack';
import Queue from '../libs/queue';
import type {SelectionOption} from '../components/DropDown';
import SideNav from '../components/SideNav';


const algorithmOptions: SelectionOption[] = [
    { value: 'dfs', label: 'Depth First Search' },
    { value: 'bfs', label: 'Breadth First Search' },
]

const Home: NextPage = () => {

    // const stack = new Stack<number>([0, 2]);
    // const queue = new Queue<number>([0, 2]);

    const [state, setState] = useState({
        sideNavVisible: false
    });

    const sideNavVisibilityToggler = () => {
        setState({ sideNavVisible: !state.sideNavVisible })
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Online Maze Game powered by AI | By Suraj Jha</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <button className={styles.sideNavToggleButton} onClick={sideNavVisibilityToggler}><MenuRoundedIcon /></button>
            <SideNav visible={state.sideNavVisible} visibilityToggler={sideNavVisibilityToggler} />
        </div>
    )
}

export default Home
