import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react";

import MenuRoundedIcon from '@mui/icons-material/MenuRounded';

import Stack from '../libs/stack';
import Queue from '../libs/queue';
import type {SelectionOption} from '../components/DropDown';
import SideNav from '../components/SideNav';
import MazeElement from '../components/MazeElement';
import Maze from '../libs/maze';


import { connect } from 'react-redux';
import { openSideNav } from '../state/actions/sideNavActions'


const Home: NextPage = ({ openSideNav }) => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Online Maze Game powered by AI | By Suraj Jha</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <button className={styles.sideNavToggleButton} onClick={openSideNav}><MenuRoundedIcon /></button>
            <SideNav />
            <MazeElement />
        </div>
    )
}




export default connect(null, {openSideNav})(Home);
